default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: cookmeister_dev
  username: cookmeister
  password: <%= ENV['COOKMEISTER_DATABASE_PASSWORD'] %>

test:
  <<: *default
  database: cookmeister_test

production:
  <<: *default
  database: cookmeister_production
  username: cookmeister
  password: <%= ENV["COOKMEISTER_DATABASE_PASSWORD"] %>
