development:
  cloud_id: <%= Rails.application.credentials.es_cloud_id %>
  user: <%= Rails.application.credentials.es_user %>
  password: <%= Rails.application.credentials.es_pass %>

test:
  host: localhost
  port: 9250
  scheme: http

production:
  host: <%= ENV['HEROKU_ELASTICSEARCH_HOST'] %>
  port: <%= ENV['HEROKU_ELASTICSEARCH_PORT'] %>
  scheme: <%= ENV['HEROKU_ELASTICSEARCH_SCHEME'] %>
