development:
  cloud_id: <%= Rails.application.credentials.es_cloud_id %>
  user: <%= Rails.application.credentials.es_user %>
  password: <%= Rails.application.credentials.es_pass %>

test:
  cloud_id: <%= Rails.application.credentials.es_cloud_id %>
  user: <%= Rails.application.credentials.es_user %>
  password: <%= Rails.application.credentials.es_pass %>

production:
  cloud_id: <%= Rails.application.credentials.es_cloud_id %>
  user: <%= Rails.application.credentials.es_user %>
  password: <%= Rails.application.credentials.es_pass %>
